export const INGREDIENTS_ADD = 'INGREDIENTS_ADD'
export const INGREDIENTS_REMOVE = 'INGREDIENTS_REMOVE'

export const INGREDIENTS_FETCH_START = 'INGREDIENTS_FETCH_START'
export const INGREDIENTS_FETCH_SUCCESS = 'INGREDIENTS_FETCH_SUCCESS'
export const INGREDIENTS_FETCH_FAILURE = 'INGREDIENTS_FETCH_FAILURE'

export const ORDER_PURCHASE_START = 'ORDER_PURCHASE_START'
export const ORDER_PURCHASE_SUCCESS = 'ORDER_PURCHASE_SUCCESS'
export const ORDER_PURCHASE_FAILURE = 'ORDER_PURCHASE_FAILURE'
export const ORDER_PURCHASE_INIT = 'ORDER_PURCHASE_INIT'

export const ORDERS_FETCH_START = 'ORDERS_FETCH_START'
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS'
export const ORDERS_FETCH_FAILURE = 'ORDERS_FETCH_FAILURE'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH'